# Generated by Django 4.0.4 on 2022-05-29 10:54

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='imgs/collection')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='imgs/collection/small')),
                ('icon_large', models.ImageField(upload_to='imgs/collection/large')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('icon', models.ImageField(upload_to=items.models.get_upload_to_path)),
                ('lowest_float', models.FloatField(blank=True, null=True)),
                ('highest_float', models.FloatField(blank=True, null=True)),
                ('stattrak', models.BooleanField(default=False)),
                ('souvenir', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='items.collection')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.rarity')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.subcategory')),
            ],
            options={
                'permissions': (('can_view_item_sub', 'Can view new item submissions'), ('can_accept_item_sub', 'Can accept item submissions.'), ('can_decline_item_sub', 'Can decline item submissions')),
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='imgs/container')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.collection')),
            ],
        ),
    ]
