# Generated by Django 4.0.3 on 2022-04-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=400)),
                ('icon_large', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DropStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=400, null=True)),
                ('icon_large', models.CharField(max_length=400, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=400)),
                ('icon_large', models.CharField(max_length=400)),
                ('lowest_float', models.FloatField(blank=True, null=True)),
                ('highest_float', models.FloatField(blank=True, null=True)),
                ('stattrak', models.BooleanField(default=False)),
                ('souvenir', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.collection')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.rarity')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.subcategory')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.update')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=400)),
                ('icon_large', models.CharField(max_length=400)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.collection')),
                ('dropstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.dropstatus')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.event')),
            ],
        ),
    ]
