# Generated by Django 4.0.4 on 2022-05-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='skinport_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
