# Generated by Django 4.0.5 on 2022-07-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_broskins_id_subcategory_broskins_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rarity',
            name='sort_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
