# Generated by Django 4.0.4 on 2022-05-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'permissions': (('can_view_support_ticket', 'Can view support tickets.'), ('can_reply_support_ticket', 'Can reply to support tickets.'), ('can_close_support_ticket', 'Can close support tickets.'))},
        ),
    ]
